#:kivy 2.3.0

<AboutScreen>:
    name: 'about_screen'

    BoxLayout:
        orientation: 'vertical'
        padding: root.width * .02, root.height * .02
        spacing: min(root.width, root.height) * .02

        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: 0.08

            Button: 
                text: 'back'
                size_hint_x: 0.2
                on_release: 
                    app.root.current = 'main_screen'
                    root.manager.transition.direction = 'right'

            Widget: 
                size_hint_x: 0.8
        
        RelativeLayout:
            size_hint: 0.8, 0.2
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}

            Label:
                text: 'About Us'
                canvas: 
                    Color:
                        rgba: 1,1,1,1
                    Line:
                        rectangle: self.x, self.y, self.width, self.height
                        width: 1

        Label:
            size_hint_y: 0.4
            text: "A wireless local PvP multiplayer word game designed to gauge the players' vocabulary knowledge while racing against other players or against time (single-player mode)."
            text_size: self.width, None

        Widget:
            size_hint_y: 0.32
