#:kivy 2.3.0
#:import Factory kivy.factory.Factory

<MainScreen>:
    name: 'main_screen'

    BoxLayout:
        orientation: 'vertical'
        padding: root.width * .02, root.height * .02
        spacing: min(root.width, root.height) * .02

        Label:
            text: 'Iskrambol Game'
            bold: 'True'
            font_size: 32
            size_hint_y: 0.4

        BoxLayout:
            orientation: 'vertical'
            size_hint_y: 0.5
            spacing: min(root.width, root.height) * .02

            Button:
                text: 'Play'
                on_release: 
                    app.root.current = 'play_screen'
                    root.manager.transition.direction = 'left'
            Button:
                text: 'Modes'
                on_release: 
                    app.root.current = 'modes_screen'
                    root.manager.transition.direction = 'left'
            Button:
                text: 'About'
                on_release: 
                    app.root.current = 'about_screen'
                    root.manager.transition.direction = 'left'
            Button:
                text: 'Exit'
                on_release: 
                    root.show_exit_popup()
        
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: 0.1
            
            Button:
                text: 'Setting'
                on_release: 
                    app.root.current = 'setting_screen'
                    root.manager.transition.direction = 'left'
            Button:
                text: 'Sound'
            Button:
                text: 'Account'
                on_release: 
                    app.root.current = 'account_screen'
                    root.manager.transition.direction = 'left'


<ExitWindow@Popup>:
    RelativeLayout:

        Label:
            text: "ARE YOU SURE TO EXIT?"
            size_hint: 0.8, 0.5
            pos_hint: {'center_x': 0.5, 'center_y': 0.75}

        Button:
            text: "NO, JUST MISCLICKED"
            size_hint: 0.8, 0.2
            pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            on_release: 
                root.close_exit_popup()

        Button:
            text: "UNFORTUNATELY, YES"
            size_hint: 0.6, 0.1
            pos_hint: {'center_x': 0.5, 'center_y': 0.15}
            on_release:
                app.close_application()
