#:kivy 2.3.0

<ModesScreen>:
    name: 'modes_screen'

    BoxLayout:
        orientation: 'vertical'
        padding: root.width * .02, root.height * .02
        spacing: min(root.width, root.height) * .02

        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: 0.08

            Button: 
                text: 'back'
                size_hint_x: 0.2
                on_release: 
                    app.root.current = 'main_screen'
                    root.manager.transition.direction = 'right'

            Widget:
                size_hint_x: 0.6

            Button: 
                text: '?'
                size_hint_x: 0.2

        RelativeLayout:

            Button:
                text: 'Modes'
                size_hint: 0.75, 0.15
                pos_hint: {'center_x': 0.5, 'center_y': 0.9}
            
            Button:
                text: 'Multiplayer'
                size_hint: 0.5, 0.08
                pos_hint: {'center_x': 0.5, 'center_y': 0.72}
            
            Button:
                text: 'Challenge'
                size_hint: 0.5, 0.08
                pos_hint: {'center_x': 0.5, 'center_y': 0.58}

            Button:
                text: 'Puzzle'
                size_hint: 0.5, 0.08
                pos_hint: {'center_x': 0.5, 'center_y': 0.44}
